# -*- coding: utf-8 -*-
"""Эккерман Наталья Сергеевна ЛР номер 7.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/16bJ2_3MHJU5RFq1kKF6_zTFvNM_bOPfP
"""

import sqlite3

conn = sqlite3.connect('Podarki2025.db')

cursor = conn.cursor()

cursor.execute('''
CREATE TABLE IF NOT EXISTS Podarki2025 (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    name TEXT NOT NULL,
    gift TEXT NOT NULL,
    price REAL NOT NULL,
    status TEXT NOT NULL
)
''')

cursor.execute('DELETE FROM Podarki2025')

gifts_data = [
    ('Эккерман Наталья Сергеевна',  'Набор посуды', 1600, 'некуплен'),
    ('Эккерман Алексей Владимирович', 'Садок', 500, 'куплен'),
    ('Эккерман Екатерина Алексеевна', 'Синтезатор', 2000, 'куплен'),
    ('Эккерман Елизавета Алексеевна', 'Книга', 300, 'куплен'),
    ('Ващук Юлия Владимирована', 'Крем для лица', 1200, 'некуплен'),
    ('Ващук Сергей Петрович', 'Пила', 1800, 'некуплен'),
    ('Байкова Кристина Анатольевна', 'Скраб', 1000, 'некуплен'),
    ('Новикова Любовь Александровна', 'Скраб', 1000, 'некуплен'),
    ('Безменова Полина Викторовна', 'Скраб', 1000, 'некуплен'),
    ('Снигур Анастасия Сергеевна', 'Набор для творчества', 4500, 'некуплен')
]

cursor.executemany('''
INSERT INTO Podarki2025(name, gift, price, status) VALUES (?, ?, ?, ?)
''', gifts_data)


conn.commit()


cursor.execute('SELECT * FROM Podarki2025')
rows = cursor.fetchall()

print(f'{"ФИО":<30}{"Подарок":<20}{"Стоимость":^10}{"Статус":<15}')
for row in rows:
    print(f'{row[1]:<30}{row[2]:<20}{row[3]:^10}{row[4]:<15}')


conn.close()

